version: 0.8.0-{build}
configuration:
- Release
- Debug
platform:
- Any CPU
os: Visual Studio 2015
install:
 - ps: |
     Add-Type -AssemblyName System.IO.Compression.FileSystem
            (new-object System.Net.WebClient).DownloadFile(
              'https://github.com/dokan-dev/dokany/releases/download/v0.8.0-RC3/DokanInstall_0.8.0_redist-RC3.exe',
              'C:\projects\dokan-dotnet\DokanInstall.exe'
            )
 - cmd: C:\projects\dokan-dotnet\DokanInstall.exe /S

before_build:
  - nuget restore
build:
  project: DokanNet.sln
  verbosity: minimal
test:
  categories:
    except:
      - Manual
      - Timing
